# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = -10
[main.params]
icon = "home"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/CaiJimmy/hugo-theme-stack"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"
